version: 2
jobs:
  build:
    docker:
      - image: gridlabd/slac-master:190825
    steps:
      - checkout
      - run:
          name: Run the simulation
          command: |
            gridlabd my_test.glm
      - store_artifacts:
          path: /root/project
      - run:
          name: Run the simulation
          command: |
            gridlabd waterheater.glm
      - store_artifacts:
          path: /root/project/trial